CREATE DATABASE IF NOT EXISTS file_explorers;
GRANT ALL PRIVILEGES ON file_explorers.* TO 'nejc'@'%';

USE file_explorers;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);